version: 2.1
jobs:
  build_and_test:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn install
      - run: yarn coverage
      - run: yarn build & yarn pack
      - run: mv ./clits-*.tgz ./clits.tgz
      - persist_to_workspace:
          root: "."
          paths:
            - ./clits.tgz
  deploy:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project
    steps:
      - attach_workspace
          at: ~/project
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn publish ./clits.tgz
orbs:
  node: circleci/node@2.1.0
workflows:
  default:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/