version: 2.1
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:14.19.1'
    working_directory: ~/project
    steps:
      - checkout
      - run: yarn install
      - run: yarn coverage
  deploy:
    docker:
      - image: 'cimg/node:14.19.1'
    working_directory: ~/project
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
      - run: npm publish --access=public

workflows:
  default:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/