jobs:
    build_and_test:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - node/install:
            install-yarn: true
            node-version: latest
        - run: yarn coverage
        - run: yarn dist
  orbs:
    node: circleci/node@x.y
  version: 2.1
  workflows:
    default:
      jobs:
        - build_and_test:
            filters:
              tags:
                only: /.*/
        - deploy:
            requires:
              - build_and_test
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/