version: 2.1
jobs:
  build_and_test:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn install
      - run: yarn coverage
      - run: yarn build
  deploy:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn publish --new-version ${CIRCLE_TAG}
orbs:
  node: circleci/node@2.1.0
workflows:
  default:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/